[package]
name = "ldjam50"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "*"
image = "*"
cgmath = "*"
cstr = "*"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
default-features = false
